<?php

namespace App\Http\Controllers;

use App\Models\TodoItem;
use Illuminate\Http\Request;

class TodoController extends Controller
{
    public function show(Request $request)
    {
        // Find all todo items in the database with complete = 0
        // Generated by Copilot by the comment above
        $todoItems = TodoItem::where("complete", 0)->get();

        // Generated by Copilot
        return view('todo-list', [
            "todoItems" => $todoItems
        ]);
    }

    // This is the method that will be called when the user submits the form in the todo-list.blade.php view
    // This method has been generated by Copilot

    // Add a test for this method
    // add a related test into tests/Feature/TodoControllerTest.php
    // Copilot didn't generate the file (was generated manually)
    // but then helped to add a test cases for this method
    public function create(Request $request)
    {
        // Generated by Copilot
        $request->validate([
            'name' => 'required|max:255',
        ]);

        // Generated by Copilot
        $todoItem = new TodoItem();
        $todoItem->name = $request->get("name");
        $todoItem->save();

        // Generated by Copilot
        return redirect("/todo");
    }

    // Hard delete a todo item from the database
    // Generated by Copilot
    public function delete(int $id)
    {
        // Add validator for the id
        // Generated by Copilot
        if (!is_numeric($id)) {
            return redirect("/todo");
        }

        // Generated by Copilot
        TodoItem::where("id", $id)->delete();

        // Generated by Copilot
        return redirect("/todo");
    }

    // Add a field complete to the todo_items table and entity
    // My note: after adding a comment above Copilot
    // has helped to add a related field into the db migration

    // Business logic was generated by Copilot
    public function complete(int $id)
    {
        // Add validator for the id
        // Generated by Copilot
        if (!is_numeric($id)) {
            return redirect("/todo");
        }

        // Generated by Copilot
        $todoItem = TodoItem::where("id", $id)->first();
        $todoItem->complete = 1;
        $todoItem->save();

        // Generated by Copilot
        return redirect("/todo");
    }
}
